### ISSUE TITLE
How to set c function pointer to detour function.

### ISSUE THREAD

**Issue by edsky** [darfink/detour-rs#18]

**Comment by edsky** [comment]
Test.set_detour(|val| val - 5);
to
Test.set_detour(c function pointer);?

**Comment by darfink** [comment]
Hi @edsky, I do not know whether you solved your problem or not, but for the sake of completeness I'll answer.
I'd say your question is more related to the semantics of Rust rather than this library.

The most obvious alternative would be to merely forward the arguments of the closure to the C function:
```rust
Test.set_detour(|arg1, arg2| c_function(arg1, arg2));
```
